name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Install Clojure tools
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        lein: 2.11.2
        clj-kondo: 2024.03.13
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Install dependencies
      run: lein deps
    
    - name: Run clj-kondo
      run: clj-kondo --lint src test
    
    - name: Check formatting
      run: lein cljfmt check
    
    - name: Run tests
      run: lein test

